# Generated by Django 3.2.13 on 2022-06-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('project_image', models.ImageField(upload_to='project_images')),
                ('urls', models.URLField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('voters', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awardsapp.profile')),
            ],
        ),
    ]
