# Generated by Django 3.2.13 on 2022-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_auto_20220614_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
